CREATE TABLE urls (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURDATE()  
);
ALTER TABLE urls
ADD COLUMN response_code INT,
ADD COLUMN h1 VARCHAR(255),
ADD COLUMN title VARCHAR(255),
ADD COLUMN description TEXT;