services:
  web:
    build:
      context: ./
    command: make start
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"
    networks:
      - base
    depends_on:
      - postgres
    environment:  
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: database_9
      DB_USERNAME: analyzer_user
      DB_PASSWORD: analyzer_password
      DATABASE_URL: postgresql://analyzer_user:analyzer_password@postgres:5432/database_9

  postgres:
    image: postgres:11.2-alpine
    environment:
      POSTGRES_USER: analyzer_user
      POSTGRES_PASSWORD: analyzer_password
      POSTGRES_DB: database_9
    ports:
      - "5432:5432"
    networks:
      - base
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data  # Исправлено: использование именованного тома

volumes:
  postgres_data:  # Том для данных PostgreSQL

networks:
  base:
    driver: bridge
