services:
  web:
    build:
      context: ./docker/web
    command: make start
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: analyzer_user
      POSTGRES_PASSWORD: analyzer_password
      POSTGRES_DB: analyzer_db
    ports:
      - "5432:5432"

  volumes:
    postgres:

