<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Мой анализатор СЕО - список страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>
  <body>
    <header class="flex-shrink-0">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
            <a class="navbar-brand" href="/">Анализатор страниц</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link" href="/">Главная</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="/urls">Сайты</a>
                  </li>
                </ul>
            </div>
      </nav>
    </header>
    <main class="flex-grow-1">
        <div class="container-lg mt-3">
            <?php if (!empty($flash['success'])): ?>
                <div class="alert alert-success" role="alert">
                    <?= $flash['success'][0]?>
                </div>
            <?php elseif (!empty($flash['error'])): ?>
                <div class="alert alert-danger" role="alert">
                    <?= $flash['error'][0]?>
                </div>
            <?php endif; ?>
            <?print_r($checkStatusCode)?>
            <?var_dump($checkData)?>
            <?/*var_dump($checks)*/?>
            <h1>Сайты</h1>
            <div class="table-responsive">
                <table class="table table-bordered table-hover text-nowrap" data-test="urls">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Имя</th>
                        <th>Последняя проверка</th>
                        <th>Код ответа</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($urls as $url):?>
                      <tr>
                        <td><?= $url['id'] ?></td>
                        <td><a href="/urls/<?= $url['id'] ?>"><?= htmlspecialchars($url['name']) ?></a></td>
                        <td>
                        <?php
                          $checkDates = null;
                          foreach ($checkData as $key => $value): 
                              if ($key == $url['id']): 
                                  $checkDates = $value;
                              endif; 
                          endforeach; 
                          $lastCheckDate = $checkDates ? $checkDates : '';
                        ?>
                          <?= $lastCheckDate ?>
                        </td>
                        <td>
                        <?php
                        $checkCodeResponse = null;
                          foreach ( $checkStatusCode as $key => $value): 
                              if ($key == $url['id']): 
                                $checkCodeResponse = $value;
                              endif; 
                          endforeach; 
                          $codeResponse = $checkCodeResponse ? $checkCodeResponse : '';
                        ?>
                        <?= $codeResponse ?>
                        </td>
                      </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </main>
  </body>
</html>
