<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </head>
  <body class="min-vh-100 d-flex flex-column">
    <header class="flex-shrink-0">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
            <a class="navbar-brand" href="/">Анализатор страниц</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"            aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="nav-link" href="/">Главная</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" href="/urls">Сайты</a>
                  </li>
                </ul>
            </div>
      </nav>
    </header>
    <main class="flex-grow-1">
      <div class="container-lg mt-3">
        <?php if (!empty($flash)): ?>
          <div class="alert alert-success" role="alert">
            <?= $flash['success'][0]?>
          </div>
        <?php endif; ?>
        <h1>Сайт: <?= htmlspecialchars($url['name']) ?></h1>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <!-- <td><?= htmlspecialchars($url['id']) ?></td> -->
                    </tr>
                    <tr>
                        <td>Имя</td>
                        <td><?= htmlspecialchars($url['name']) ?></td>
                    </tr>
                    <tr>
                        <td>Дата создания</td>
                        <td><?= date("d.m.Y h:m:s", strtotime($url['created_at'])) ?></td>
                    </tr>
                </tbody>
            </table>
            <h2 class="mt-5 mb-3">Проверки</h2>
            <form method="post" action="/urls/<?= $id ?>/checks" class="mb-2">
                <input type="submit" class="btn btn-primary" value="Запустить проверку">
            </form>
            <table class="table table-bordered table-hover" data-test="checks">
              <thead>
                <tr>
                  <th>ID</th>
                  <th>Код ответа</th>
                  <th>h1</th>
                  <th>title</th>
                  <th>description</th>
                  <th>Дата создания</th>
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
        </div>          
      </div>
    </main>
  </body>
</html>
            