<main class="flex-grow-1">
  <div class="container-lg mt-3">
    <?php if (!empty($flash['success'])): ?>
            <div class="alert alert-success" role="alert">
                <?=$flash['success'][0]?>
            </div>
      <?php elseif (!empty($flash['error'])): ?>
            <div class="alert alert-danger" role="alert">
                <?=$flash['error'][0]?>
            </div>
        <?php endif; ?>
    <h1>Сайт: <?= htmlspecialchars($url['name']) ?></h1>
    <div class="table-responsive">
        <table class="table table-bordered table-hover text-nowrap" data-test="url">
            <tbody>
                <tr>
                    <td>ID</td>
                    <td><?= htmlspecialchars($url['id']) ?></td>
                </tr>
                <tr>
                    <td>Имя</td>
                    <td><?= htmlspecialchars($url['name']) ?></td>
                </tr>
                <tr>
                    <td>Дата создания</td>
                    <td><?= htmlspecialchars($url['created_at']) ?></td>
                </tr>
            </tbody>
        </table>
        <h2 class="mt-5 mb-3">Проверки</h2>
        <form method="post" action="/urls/<?= $id ?>/checks" class="mb-2">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
        </form>
        <table class="table table-bordered table-hover" data-test="checks">
          <thead>
            <tr>
              <th>ID</th>
              <th>Код ответа</th>
              <th>h1</th>
              <th>title</th>
              <th>description</th>
              <th>Дата создания</th>
            </tr>
          </thead>
          <tbody>
          <?php if(!empty($checks)):?>
          <?php $numCheck = count($checks) ?>
          <?php foreach ($checks as $check):?>
            <tr>
              <td><?= htmlspecialchars($numCheck)?></td>
              <td><?= htmlspecialchars($check['status_code'])?></td>
              <td><?= htmlspecialchars($check['h1'] ?? '-') ?></td>
              <td><?= htmlspecialchars($check['title'] ?? '-') ?></td>
              <td><?= htmlspecialchars($check['description'] ?? '-') ?></td>
              <td><?= $check['created_at'] ?? '' ?></td>
            </tr>
            <?php $numCheck-- ?>
          <?php endforeach; ?>
          <?php endif; ?>
          </tbody>
        </table>
    </div>
  </div>
</main>
