<h1>Анализатор страниц</h1>

<?php if (!empty($flash)): ?>
    <p style="color: red"><?= $flash['error'][0]?></p>
<?php endif; ?>
<p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
<form action="/urls" method="post" class="row">
    <div class="col-8">
            <label for="text" class="visually-hidden">Url для проверки</label>
            <input type="text" name="url[name]" value="" class="form-control form-control-lg" placeholder="https://www.example.com">
    </div>
    <div class="col-2">
                <input type="submit" class="" value="Проверить">
    </div>
</form>
